### ISSUE TITLE
Add configuration option for security paths

### ISSUE THREAD

**Issue by wouterj** [symfony-cmf/resource-rest-bundle#45]
Currently, one has to write a security voter in order to allow access to some paths. It would be much nicer if people can configure the allowed paths with configuration instead:

```yaml
cmf_resource_rest:
    security:
        allow:
            - { path: /cms/public }
            # ...
```
